package com.example.readdit.database

enum class TopicEnum {
    ARTS, CREATIVITY, CODING, DECISION_MAKING, HABITS, HEALTH, HOBBIES, FINANCE, FOODS, LIFE_LESSONS, MOTIVATION, MEDITATION, PRODUCTIVITY, RELATIONSHIP
}